### ISSUE TITLE
arrow-parens

### ISSUE THREAD

**Issue by Di-did-done** [positive-js/tslint-config#12]
Предлагаю использовать это правило таким образом, чтобы в arrow functions всегда аргументы были в скобках, независимо от их количества.

Т.е. вместо `const double = x => x * 2` писать `const double = (x) => x * 2`

Это приведет к единообразному написанию, также мне кажется, что такая запись лучше читается. Ну и плюс убережет от ошибок, когда будут добавляться новые параметры в функцию с одним аргументом.

**Comment by srg985** [comment]
Идея нравится. Без скобок в глазах сливается от знаков "равно".

**Comment by AKolodeev** [comment]
👍 Плюс, чтобы задавать тип аргумента и возвращаемое значение скобочки необходимы.

**Comment by dmalshin** [comment]
https://github.com/airbnb/javascript#arrows--implicit-return Комьюнити поддерживает (частично)
