### ISSUE TITLE
interface-name

### ISSUE THREAD

**Issue by Di-did-done** [positive-js/tslint-config#16]
Предлагаю еще подискутировать на тему должны ли интерфейсы начинаться с буквы I.

Вопрос возник из-за того, что в Angular Style Guide https://angular.io/guide/styleguide#interfaces
написано следующее:

> Consider naming an interface without an I prefix.

И они ссылаются на https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

У нас же сейчас в правилах написано наоборот:
<pre>"interface-name": {
    options: ["always-prefix"]
 }</pre>

**Comment by dmalshin** [comment]
Microsoft использует I

https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/diff/diff.ts

**Comment by imrekq** [comment]
Я за то, чтобы начинались с I. Боюсь лайкать, т.к. не понятно за что голосую.

**Comment by srg985** [comment]
Скажем так, префиксирование буквой I иногда выглядит странно. Например, вот так выглядит определение набора некоторых сущностей например (все герои вымышлены, совпадения случайны):

```typescript
const topologyList: ITopologyItem[];
```
Или не использовать интерфейсы для определения структур данных...  Но это нельзя, потому что у нас действует ещё одно правило: `interface-over-type-literal` https://palantir.github.io/tslint/rules/interface-over-type-literal/

**Comment by imrekq** [comment]
@srg985 а почему странно? объявление массива сущностей, обладающих определенным фейсом...

**Comment by srg985** [comment]
Это на уровне ощущений.

Вот так видится хорошо:
```typescript
class BitcoinFarmFabric implements IPoleChudes {}
```

Но при определении наборов данных конечные типы как-то ожидаются что ли как-то вот.

```typescript
const buratinoFriends: DummyFellow[] = [];
```

**Comment by Di-did-done** [comment]
Ну как я вижу большинство сошлось на использовании префикса I, так что закрываю issue
