### ISSUE TITLE
Указание типов массивов через generic

### ISSUE THREAD

**Issue by srg985** [positive-js/tslint-config#2]
Предлагаю типы массивов указывать как `Array<T>`. Настройка в конфиге тогда меняется:

```typescript
"array-type": [
    true,
    "generic"
]
```

**Comment by Norf-g** [comment]
По моему писать string[] удобнее

**Comment by srg985** [comment]
@Fost Предложение перейти на запись Type[] вместо Array[Type] уже было. Тогда ты приводил какой-то аргумент за Array[Type]?

**Comment by imrekq** [comment]
Я за Array<T>. Т.к. в ts ts есть generics и для унификации объявления использовать <>.

**Comment by srg985** [comment]
Так же поддерживаю запись Array<TYPE>.

**Comment by pimenovoleg** [comment]
#3

**Comment by Di-did-done** [comment]
Спрошу у всех участвующих в обсуждении, в чем профит использовать запись вида Array\<Type\> вместо Type[]?

Я вот абсолютно не вижу в этом смысла, по-моему второй вариант намного проще в написании, да и в понимании тоже

**Comment by Norf-g** [comment]
Не могу понять. Вроде все говорили о том что string[] удобнее. В мерж реквесте же обсуждали
https://gitlab.ptsecurity.com/ui/maxpatrol-9/merge_requests/1806

**Comment by imrekq** [comment]
`Type[]`
+ Лаконичность
+ Частично удобочитаемость (дело привычки)

`Array<type>`
+ Унифицированность, т.к. в ts есть еще generics
+ Частично удобочитаемость (название типа может быть длинным в случае классов, а тут мы сразу видим, что это массив - первично, а тип дальше)

На внутреннем уровне различий вроде нет. Вопрос уже поднимается третий раз - надо бы уже прийти к соглашению)

**Comment by Di-did-done** [comment]
Ну может тогда и создавать их будем как `new Array()` для унифицированности записи массивов?)

По-моему, это более короткая и всем понятная запись.
А про длинные имена, ну не знаю, насколько имя должно быть длинным, чтобы полностью не видеть запись Type[].

Плюс, если тебе надо будет создать массив generic типа, то запись
`Array<GenericType<T>>`, как по мне, уступает в удобочитаемости `GenericType<T>[]`, но это лично мое мнение.

Я бы здесь доверилась tslint:recommend и tslint-microsoft-contrib

**Comment by srg985** [comment]
`GenericType<T>[]` - насколько такая форма записи вообще принята?

**Comment by Di-did-done** [comment]
Настолько же, насколько принята string[], а в чем должно быть принципиальное отличие?

Например вот, https://github.com/ngrx/platform/blob/master/modules/store/src/models.ts#L33

**Comment by srg985** [comment]
При записи "сложных типов" конструкция с Array выглядит более удобочитаемой, хоть и более громоздкой. 
```typescript
const values: (object | number)[] = []
const values: Array<object | number> = []
```
Иногда сокращения написанного затрудняют уже восприятие. Например, как в случае с опусканием скобок при единочном аргумента arrow function - вроде запись короче, а читается хуже, особенно если слева тоже знак равно и справа после `=>` сразу выражение. #12 

#мысливслух

**Comment by srg985** [comment]
Вот ещё прекрасный пример насколько просаживается удобочитаемость при более сложных конструкциях.

Запись через Array:
```typescript
Array<{length: number, deferred: Deferred<any[]>}>
Array<Document|string>
Array<(event: Event) => void>
TableRow<Array<string|number|null>>
```

Оно же без Array:
```typescript
{length: number, deferred: Deferred<any[]>}[]
(Document|string)[]
((event: Event) => void)[]
TableRow<(string|number|null)[]>
```

**Comment by Di-did-done** [comment]
Ну скажем так, я считаю, что так писать вообще не надо и вопрос удобочитаемости тут уже не в Array или []

**Comment by Norf-g** [comment]
Во-первых Андрей, такая запись занимает 0.01% от общего использования типов массивов. и крайние случаи мы не берем в расчет. И не могу придумать примера для использования "|" в типах.

**Comment by srg985** [comment]
Я сходу тоже придумать не могу, но вот этот пример последний он вроде из реального проекта, я его нашел как раз с вопросом на тему лучшей записи.
Типы мы пока не использовали почти вообще, но надеюсь, что типизацию мы когда-нибудь доведем до уровня абсолюта, и тогда родятся и такие конструкции. А мы к ним уже готовы.

**Comment by srg985** [comment]
Ну вот, вопрос ещё раз решен - теперь пишем без Array :)
