### ISSUE TITLE
object-literal-key-quotes: as-needed

### ISSUE THREAD

**Issue by cooleso** [positive-js/tslint-config#24]
object-literal-key-quotes: as-needed

**Comment by cooleso** [comment]
сейчас стоит consistent, смотрится не очень

**Comment by srg985** [comment]
Поддерживаю, кавычить только когда надо.

**Comment by pimenovoleg** [comment]
@cooleso , @srg985  - cделайте PR

**Comment by srg985** [comment]
@Fost MR created https://github.com/positive-js/tslint-config/pull/28
