### ISSUE TITLE
Правило "blank-lines" не работает в вебшторме

### ISSUE THREAD

**Issue by cooleso** [positive-js/tslint-config#25]
![screenshot_206](https://user-images.githubusercontent.com/977580/34046779-39b5ad4c-e1bf-11e7-8e72-84ce9e8b3224.png)
![screenshot_205](https://user-images.githubusercontent.com/977580/34046783-3d849460-e1bf-11e7-8640-6d69722b45e9.png)

**Comment by Di-did-done** [comment]
Тут дело не в вебшторме, а в разделителях строк.

Я уже сделала фикс (#22), в следующем пакете должно всё заработать
