### ISSUE TITLE
newline-before-return

### ISSUE THREAD

**Issue by cooleso** [positive-js/tslint-config#27]
Не очень нравится - в небольших функциях на несколько строк пустая строчка кажется лишней.

**Comment by lskramarov** [comment]
Если в функции только return то пустая строка не нужна, если есть другие блоки то нужно отделять return пустой строкой.

например:
```
function foo() {
    return;
}

function foo(bar) {
    if (!bar) { return };
}

function foo(bar) {
    if (!bar) {
        return;
    }
}

function foo(bar) {
    if (!bar) { return; }

    return bar;
}
```

**Comment by pimenovoleg** [comment]
@lskramarov сделаешь PR на правило?

**Comment by imrekq** [comment]
На текущий момент правило включено по умолчанию, отрабатывает согласно кейсу @lskramarov .
