### ISSUE TITLE
Конфликт prettier и [blank-lines]

### ISSUE THREAD

**Issue by dmalshin** [positive-js/tslint-config#30]
Prettier убирает пустые строки свыше одной при форматировании.

В конфиге есть правило "[tslint] You need to use 2 consecutive blank lines after imports (blank-lines)"

Может уберем это правило? Одно строки как по мне - достаточно.

Посмотрел проекты на TS в открытом доступе - везде одна строка после импорта.

**Comment by imrekq** [comment]
Есть еще идея развести prettier (только на js), а ts-файлы обслуживать tslint --fix'ом (дописав formatter'ы под нужные правила)

**Comment by pimenovoleg** [comment]
@dmalshin 

мы стараемся брать практики из pep8.
2 строки хорошо разграничивают область импорта и кода.

Отдельна есть проблема с конфликтом prettier - этим в ближайшее время будет заниматься @imrekb
