### ISSUE TITLE
no-backbone-get-set-outside-model

### ISSUE THREAD

**Issue by imrekq** [positive-js/tslint-config#31]
Насколько нам необходимо данное правило? Может отключим?
Столкнулся с ним на `this.$templateCache.get('bla-bla.tpl.html');`

**Comment by imrekq** [comment]
Предлагаемое решение https://github.com/positive-js/tslint-config/pull/32

**Comment by Di-did-done** [comment]
Да, согласна, надо отключить.

**Comment by srg985** [comment]
Не сталкивался, так что не возражаю.
