### ISSUE TITLE
trailing-comma: multiline: "always"

### ISSUE THREAD

**Issue by evilfant** [positive-js/tslint-config#36]
Выставить у правила `trailing-comma` значение `multiline: "always"`  

Сейча значение [mulitline: "newer"](https://github.com/positive-js/tslint-config/blob/553bc0137082a2c22304d6152ce88b664cb0a421/src/configs/tslint-override.ts#L77) 

О плюсах такого правила можно потчитать [тут](https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8)

**Comment by srg985** [comment]
Идея любопытная, выгода понятна. Но повисшие "в конце" запятые напрягают глаз. Возможно с непривычки. Может поставить ignore чтоб можно было выборочно экспериментировать?

**Comment by evilfant** [comment]
ignore приведет к "каждый пишет как хочет" и породит хаос
А привычка - дело времени, причем малого. Я в своих проектах не пишу `;` и использую табы, хотя на работе везде пробелы и `;` и боль была только первые часы
