### ISSUE TITLE
Сделать public обязательным.

### ISSUE THREAD

**Issue by Dangel84** [positive-js/tslint-config#39]
Предлагаю сделать указание модификатора доступа **public** обязательным путем задания
_"member-access": true_

Я понимаю, что технически это не обязательно, и все члены класса имеют модификатор **public** по умолчанию, однако считаю это очень важным с точки зрения дисциплины и восприятия кода.

Почему?
Боюсь, что иначе многие будут лениться или забывать указывать модификаторы доступа вообще, т. к. это никак не мешает компиляции и работе программы. :(

Как я рассказывал в своем докладе, Инкапсуляция одна из ключевых концепций ООП и правильное проектирование классов невозможно без ее соблюдения. 
По-хорошему, разработчик при добавлении любого поля/метода класса должен сразу планировать зачем он добавляет это в класс, "Это часть имплементации или часть интерфейса класса, кто может иметь доступ к этому?" Обязательность модификаторов доступа очень хорошо этому способствует и дисциплинирует при написании кода.
Особенно это будет полезно для людей без опыта ООП программирования, т.к. помогает быстрее начать мыслить в соответствующей парадигме.

Так же (по крайней мере на мой взгляд), наличие модификатора **public** улучшает восприятие кода. Можно открыть класс и с одного взгляда, по ключевому слову public вычленить интерфейс работы с ним. (Да, часто класс открывается только для того чтобы узнать, как с ним работать.)

**Comment by pimenovoleg** [comment]
The previously described rules exclude this approach
