### ISSUE TITLE
import-name

### ISSUE THREAD

**Issue by AKolodeev** [positive-js/tslint-config#43]
Предлагаю отключить правило или добавить исключения, т.к. в текущих реалиях оно только вредит. Например:
1. Есть legacy-код, использующий `export default`:
```ts
import IncidentsAttackService from './incidents-attack.service';
```
"Правильным" именем будет `incidentsAttackService`.

2. Используется импорт из scoped-пакета:
```ts
import uiRouter from '@uirouter/angularjs';
```
"Правильным" именем будет `angularjs`.

**Comment by evilfant** [comment]
👍

**Comment by missfox** [comment]
👍
