### ISSUE TITLE
no-implicit-dependencies

### ISSUE THREAD

**Issue by AKolodeev** [positive-js/tslint-config#44]
Есть проблемы при использовании типизации, которая идет отдельным пакетом.

Например,
```ts
import { IFlow, IFlowOptions, IFlowFile } from 'flowjs';
import { IGridOptions, IGridApi } from 'ui-grid';
```
В данном случае, правило не учитывает, что типы берутся из `@types`.

Решить можно, либо сделав исключения на уровне конкретного проекта, либо настроив правило.

**Comment by pimenovoleg** [comment]
да, делается на уровне проекта
