### ISSUE TITLE
no-console setting

### ISSUE THREAD

**Issue by srg985** [positive-js/tslint-config#5]
Буду краток, предлагаю:
```typescript
"no-console": [false]
```

Или хотя бы
```typescript
"no-console": [true, "log"]
```

**Comment by srg985** [comment]
Напоминаю о теме.
@krylova-dinara @norf33rus @Fost @imrekb

**Comment by imrekq** [comment]
`"no-console": [true, "log", "debug"]` ?

**Comment by srg985** [comment]
Мне бы хватило даже `"no-console": [true, "debug"]`
Для отладки хватит debug, и потом вычищать удобно, проведя поиск.

**Comment by imrekq** [comment]
debug и log вроде бы синонимы, и если их исключать, то наверно бы оба.

**Comment by Di-did-done** [comment]
А зачем использовать debug, если есть log?

**Comment by imrekq** [comment]
дело вкуса, наверно) я использую лог, но в любом случае - исключать оба.

**Comment by Di-did-done** [comment]
Ну ок, я за `"no-console": [true, "log", "debug"]`

**Comment by srg985** [comment]
>  А зачем использовать debug, если есть log?

debug Более соответствует назначению, всё же log это не всегда только для разработки, иногда бывает лог-вывод и в продакш коде (зачем не знаю, но может быть).
А debug это строго для отладки, глаз спотыкается об него, и потом искать проще для очиски кода в конце разработки.

**Comment by srg985** [comment]
> debug и log вроде бы синонимы, и если их исключать, то наверно бы оба.

Формат вывода -- одинаковый, а сами вызовы не совсем одно и то же с точки зрения фильтрации в консоли. При отключенном Verbose выводы log показываются, а выводы debug нет.

![image](https://user-images.githubusercontent.com/4182548/33601251-b5a5eb84-d9bc-11e7-93aa-3c507e3f4e25.png)

**Comment by srg985** [comment]
Есть два вопроса:

1.Возможно ли вообще попадание в prod кода с какими-то вызовами console.<xxx>? При том, что у нас вроде как для вывода в консоль не-для-разработки есть $log- обёртка.

2.Данное правило оно для чего? Чтобы обеспечить в коде наличие только тех вызовов console которые могут попасть в prod (при условии, что п.1 их разрешает вообще)? Или чтобы вообще исключить использование вызовов console даже для отладки при разработке?

Если мы запретим использовать console вообще, то программисты будут его использовать с `// tslint:disable-line` и защита не сработает. Если разрешить один метод `debug`, то в prod его не пустит uglify (в нём есть опция убирания console.debug), а tslint будет подстраховывать от использования тех вызовов которые не перехватывает uglify.

**Comment by srg985** [comment]
> Ну я считаю, что методы warn и error вполне могут использоваться в prod-версиях.

@krylova-dinara  Для prod они будут использованы через обёртку `$log`

**Comment by Di-did-done** [comment]
Данное правило для того, чтобы в prod не просочились твои log и debug, которые ты использовал для разработки/отладки и т.д.

Для production как мне кажется вполне могут пригодиться error и warn.
Обертку $log я бы не использовала, лишняя зависимость от AngularJS, да и в Angular пока эквивалента нет.

Тем более, возможно что ты захочешь использовать логгер, вне DI AngularJS

Console - это нативный способ вывести что-то в консоль с нужным тебе приоритетом, почему бы его не использовать?

**Comment by Di-did-done** [comment]
Даже не совсем так сказала, это правило чтобы в сам репозиторий не смогли просочиться твои log и debug, а uglify от этого тебя никак не спасет

**Comment by srg985** [comment]
> Обертку $log я бы не использовала

В свое время о необходимости использовать эту обёртку не для временного кода мне четко говорилось.

> Console - это нативный способ вывести что-то в консоль с нужным тебе приоритетом, почему бы его не использовать?

Есть правило, запрещающее консоль. То есть что-то запретить надо. Иначе зачем такие правила писать. Если бы это был фильтр только в сборщике для prod, то я бы запретил всё. Но этот линтер будет проверять всё и всегда во время разработки. Отказаться совсем от console я не считаю верным. Использовать постоянно отключалки линтера для строки это всё равно, что это правило вообще не писать и оставить как есть. Т.к. IMHO линтер это больше инструмент-подсказка для разработчика в процессе его работы, а не фильтр на уровне сборщика CI.

**Comment by Di-did-done** [comment]
> В свое время о необходимости использовать эту обёртку не для временного кода мне четко говорилось.

Не знаю, когда это было, я такого не слышала и никогда ее не использовала, но я в принципе нигде не использовала в prod методы из console. Но в mosaic вижу использование console.warn и не вижу в этом ничего плохого.

> Отказаться совсем от console я не считаю верным. Использовать постоянно отключалки линтера для строки это всё равно, что это правило вообще не писать и оставить как есть.

Этот линтер, по крайней мере у меня, проверяет код перед коммитом и поэтому не позволяет тебе именно закоммитить такие вещи.
Я уже давно живу с правилом `"no-console": [true, "log"]` и никогда его не отключала с помощью комментов и вообще не понимаю зачем это делать? 
Код у тебя запустится, даже если в линтере есть ошибки, просто будет подчеркивать красным, напоминая о том, что это надо будет убрать

>  Т.к. IMHO линтер это больше инструмент-подсказка для разработчика в процессе его работы, а не фильтр на уровне сборщика CI.

Да, это инструмент, который говорит тебе как писать код. И он говорит, что в твоем окончательном варианте не должен использоваться log или debug. Он ни в коем случае не должен попасть в репозиторий, вот в чем смысл.

@srg985 давай так, ты хочешь чтобы у тебя в репозиторий попадали строчки console.log и console.debug?

**Comment by srg985** [comment]
> Код у тебя запустится, даже если в линтере есть ошибки, просто будет подчеркивать красным, напоминая о том, что это надо будет убрать

Не, красный линтер это повод что-то исправить. Если файл будет перманентно краснеть из-за известных console, можно проморгать другие проблемы. Считаю к красному линтеру привыкать не надо.

> давай так, ты хочешь чтобы у тебя в репозиторий попадали строчки console.log и console.debug?

Если речь о фича-ветках, то конечно пусть будут. В фича ветках может быть ещё что-то кроме console, что не должно быть влито в релизную ветку.

**Comment by Norf-g** [comment]
> Считаю к красному линтеру привыкать не надо. 

И поэтому он тебе будет постоянно говорить, чтобы ты убрал это, и это правильно!

**Comment by Di-did-done** [comment]
> Не, красный линтер это повод что-то исправить. 

Совершенно верно и использование console.log в коде - это повод его оттуда убрать, когда он тебе больше не нужен. Потому что по собственной практике могу сказать, что бывает, что об этом совершенно забываешь.

> Если речь о фича-ветках, то конечно пусть будут. В фича ветках может быть ещё что-то кроме console, что не должно быть влито в релизную ветку.

А в чем здесь принципиальная разница? И что самое интересное, когда ты будешь определять, что вот теперь console надо убрать. И можешь ли ты дать 100% гарантию, что ты об этом не забудешь?
Я вот уверена, что нет.

В общем, я свое мнение высказала, мне больше сказать нечего

**Comment by imrekq** [comment]
Аргументы исчерпаны вроде. Давайте голосовать! Вопрос в студии: запрещаем(заставляем линтер ругать за это) использование console.log и console.debug?
Профит: меньше вероятность выпустить это в продакшн-код.
`"no-console": [true, "log", "debug"]`

**Comment by srg985** [comment]
Я не представляю как можно запретить повседневные средства отладки, ничего не предложив взамен. Я могу выкрутиться через `console.log(); // tslint:disable-line`, но это какбэ говорит "моя на правило покласть". Моя идея была в том, чтобы разрешить один единственный вызов console который эффективно выцеживается из production уже имеющимися инструментами, а остальные запретить. При этом можно писать код, не спотыкаясь глазами о красные подчеркивания дебажных выводов, которые могут торчать в коде прям всю фичу (месяц, два...)

Тогда уж проще не запрещать console, чтоб не создавать правило которое будет построянно не исполняться.

**Comment by Norf-g** [comment]
Ребята, ребята. Просто вопрос который поставил Олег, немного неправильно сформулирован. Мы можем это использовать при разработке! НО! Линтер будет постоянно говорить мол, убери этот console.... и это правильно! Понял что находится в этой переменной. Убрал. Такой кейс. И при коммите, ты не сможешь пройти мимо линтера, т.к. он замозолит твои глаза. Поэтому я считаю правильно то, что линтер должен ругаться на подобные конструкции.

**Comment by Norf-g** [comment]
И я не за запрет использования, но за это правило!

**Comment by imrekq** [comment]
Конечно же. Запрещаем != Не используем.

**Comment by srg985** [comment]
Интересно, а можно для релизных веток свою конфигу линтера прикрутить к тем же сборщикам? У нас по-моему есть ряд вещей, типа чекера формата коммит-месседжей, которые на фича- и багфикс-ветках не нужны. Можно было бы сделать два профиля и линтера: продакшн и дев. Идея же не нова разделять настройки окружения на dev и prod.

**Comment by srg985** [comment]
> Линтер будет постоянно говорить мол, убери этот console.... и это правильно!

@norf33rus В одной из недавних фич некоторые дебажные выводы висели почти все время работы над фичей (2-3 мес). Это не удобно когда ошибки мозолят глаза неделями или месяцами. Даже вредно. А если я привыкну, что линтер может ругаться, но это не повод сразу обратить внимание - я обязательно очень быстро проморгаю реальные ошибки и вообще усвою мысль, что красный линтер это всего лишь красный линтер.
Моя идея в том, что есть два вредных явления которые лучше не допускать:
1.Длительно работать в условиях когда индикация ошибки это "на самом деле не ошибка, а просто так надо, но потом я уберу" (всё равно, что ездить с горящей лампой check engine).
2.Точечно обходить игнор-директивами правила линтера для соблюдения п.1 (отсоединить проводок, чтоб лампа не загоралась).

Так же я исходил из того, что консольный вывод в prod никогда не требуется, что console это исключительно дебажный вывод в процессе разработки или фиксов, поэтому ценности в log, info, warn и error нет.
Отсюда и все мои предложния.
Ну а там как решит Собор.

**Comment by Norf-g** [comment]
1. Если даже подуть о 2х сборках, то когда разработчик замержит console в релизную ветку. И будет собирать, а она упадёт, то тогда получится, что будут коммиты вида remove console. Сам там делал.Что не есть хорошо.
2. Думаю когда console живет 2 месяца, то значит что-то не так.
@Fost Олег, рассуди пожалуйста), а то потонем)

**Comment by srg985** [comment]
Не потонем совсем, вот голосование, и результат вполне однозначный. Можем ещё поговорить, но вопрос IMHO решён: https://github.com/positive-js/tslint-config/issues/5#issuecomment-349359141

**Comment by srg985** [comment]
> Если даже подуть о 2х сборках, то когда разработчик замержит console в релизную ветку.

Вроде можно повесить линтер на мерж в определенную ветку. Тем более, что чекер коммит-месседжей тоже собирались прикрутить не как сейчас на все коммиты, а только когда делается коммит в релизные ветки. #offtopic

**Comment by Di-did-done** [comment]
@srg985 если вопрос решен и результат вполне однозначный, то почему вместо
`"no-console": [true, "log", "debug"]` ты в PR пишешь ` "no-console": true` ?

**Comment by lskramarov** [comment]
я за "no-console": [true, "log", "debug"], warn и error могут пригодиться, сейчас их рубить не стоит...

**Comment by pimenovoleg** [comment]
> Ну я считаю, что методы warn и error вполне могут использоваться в prod-версиях.

warn оставить нужно точно.
Ошибки надо "бросать" через throw new Error('...')

**Comment by srg985** [comment]
@krylova-dinara Ошибся конечно... Все силы уходят на комменты, на код не остаётся.
Поправил PR.

**Comment by srg985** [comment]
Учтено замечание @Fost 
> Ошибки надо "бросать" через throw new Error('...')

Текущая настройка:
```typescript
"no-console": [true, "log", "debug", "error"]
```
