### ISSUE TITLE
Правила из rxjs-tslint-rules

### ISSUE THREAD

**Issue by Dangel84** [positive-js/tslint-config#51]
Есть вопросы по добавленым правилам.
'rxjs-no-add', 'rxjs-no-patched', 'rxjs-no-wholesale' - не актуальны для 6 версии, о чем линтер сам и пишет.

`rxjs-no-add is deprecated. Rule not needed for v6.
rxjs-no-patched is deprecated. Rule not needed for v6.
rxjs-no-wholesale is deprecated. Rule not needed for v6.`

По 'rxjs-no-finnish' - а есть обоснования для этого решения?
Вообще синтаксис типа name$ для полей типа Observable довольно распространен и популярен. (Тот же ngrx его активно использует во всех примерах.) И это действительно удобно, когда в разметке сразу видишь к кому надо привязываться с async а к кому нет.

**Comment by pimenovoleg** [comment]
name$ - да, это удобно

в чем предложение? Можно зразу PR :)

**Comment by pimenovoleg** [comment]
@Dangel84

**Comment by RistiCore** [comment]
`rxjs-no-wholesale` не совместим с [официальной рекомендацией](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#import-paths) по импорту того же Subject:
```typescript
import { Subject } from 'rxjs';
```

**Comment by Dangel84** [comment]
Вот этот коммит добавил некоторые правила https://github.com/positive-js/tslint-config/commit/438fbaf
Предлагаю большую их часть убрать. Т.к.
'rxjs-no-add', 'rxjs-no-patched', 'rxjs-no-wholesale' - не актуальны для 6 версии
 'rxjs-no-finnish'  - запрещает такой синтаксис (name$).

**Comment by RistiCore** [comment]
В общем так: #52
