### ISSUE TITLE
Add typedef rule

### ISSUE THREAD

**Issue by evilfant** [positive-js/tslint-config#56]
Current `typedef` rule values is `false` because of [tslint:recommended](https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts#L147)  
my suggestion is
```json
"typedef": [
    true,
    "call-signature",
    "parameter",
    "property-declaration",
    "variable-declaration",
    "member-variable-declaration"
]
```

**Comment by imrekq** [comment]
This rule is high-costed. It is very good for projects without legacy. Otherwise, code after the rule will be very red and would need a lot of time that fix it. If your project has small code-base and modern that you can to enable this rule on project-level.
