### ISSUE TITLE
max-func-body-length

### ISSUE THREAD

**Issue by srg985** [positive-js/tslint-config#6]
Упёрся в максимальный рекомендованный размер функции (в строках, 100 строк). 
У меня actions обернуты общей функцией внутри которой как функции-генераторы actions, так и thunk-функции. То есть уйти за 100 строк при такой вложенности запросто.
Как будем решать?
Вариант 1: оставить ограничение 100 строк и искать пути уменьшения фукнции-обёртки (выносить из нее мелкие функции за скоуп и т.п.)
Вариант 2: убрать ограничение 100 строк или сделать его 250 строк например.

Подробнее о данном параметре прочитать тут: https://github.com/Microsoft/tslint-microsoft-contrib

**Comment by imrekq** [comment]
Я за более детальную декомпозицию, т.к. большие атомарные функции - все таки как исключения, многое успешно разносится.

**Comment by srg985** [comment]
Давайте попробуем оставить как есть, 100 строк.
