### ISSUE TITLE
no-reserved-keywords

### ISSUE THREAD

**Issue by srg985** [positive-js/tslint-config#8]
У нас немало ещё есть данных которые лежат под ключами с именами, совпадающими с reserved keywords.

![image](https://user-images.githubusercontent.com/4182548/33382432-c86a959c-d531-11e7-8dc0-65ca9b7520ac.png)

Предложение:

1.Постепенно отказываться от reserved keywords в контрактах. 
2.Из-за наличия legacy добавить следующую настройку в конфигурацию tslint-microsoft-config-override.ts:
```typescript
"no-reserved-keywords": [
  true,
  "allow-quoted-properties"
]
```

**Comment by Di-did-done** [comment]
Может быть как-то дописать правило, чтобы можно было бы исключать некоторые слова из проверки? потому как слово 'type' в контрактах используется очень часто и вряд ли получится его полностью искоренить. 

Также в redux оно используется, например в такой записи: `const { type, payload } = action;`

**Comment by pimenovoleg** [comment]
в случае API, эта зона на которую мы не можем влиять.
Есть практика создания *.d.ts описывающие внешние контракты.
