### ISSUE TITLE
no-magic-numbers

### ISSUE THREAD

**Issue by srg985** [positive-js/tslint-config#9]
Имеем блок кода в обработчике коллективного промиса Promise.all
```typescript

dispatch(_topologyEditorDataLoadSuccess({
    topologyEditorData: loadedData[0],
    assetsSelected: loadedData[1],
    assetgroupsSelected: loadedData[2]
}));
```
Линтер ругается на loadedData[2] - говорит `no-magic-numbers`. Ваше мнение, законно ли его требование и как обойтись без этих намберов в данном случае?

**Comment by imrekq** [comment]
Как обойтись:
1) Очевидное, но не эстетическое - вынести цифры в константы: `indexTopologyEditorData, ...`
2) Использовать destructuring assignment: 
```
const [topologyEditorData, assetsSelected, assetgroupsSelected] = loadedData;
dispatch(_topologyEditorDataLoadSuccess({
    topologyEditorData,
    assetsSelected,
    assetgroupsSelected
}));
```

**Comment by srg985** [comment]
Мне нравится вариант 2. 
Индексы в константы ради линтера это немного слишком.
